In [1]:
%pip install numPy


Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(arr)
arr[:,2]=1

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [11 12  1 14 15]
 [16 17  1 19 20]]


In [10]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
np.fill_diagonal(arr,0)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [14]:
arr = np.arange(1,37).reshape(6,6)
print(arr)
arr1=arr[3:6,2:5]
print(arr1)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[21 22 23]
 [27 28 29]
 [33 34 35]]


In [19]:
arr=np.random.randint(1,100,size=(3,4))
arr2=np.random.randint(1,100,size=(3,4))
print('addition',arr+arr2)
print('subtraction',arr-arr2)
print('multiplication',arr*arr2)    
print('division',arr/arr2)

addition [[162  88 160 121]
 [ 40  62 195  77]
 [ 60  57 109 167]]
subtraction [[  6 -76  34  69]
 [  4 -14   1  75]
 [ -2 -51 -69  23]]
multiplication [[6552  492 6111 2470]
 [ 396  912 9506   76]
 [ 899  162 1780 6840]]
division [[1.07692308e+00 7.31707317e-02 1.53968254e+00 3.65384615e+00]
 [1.22222222e+00 6.31578947e-01 1.01030928e+00 7.60000000e+01]
 [9.35483871e-01 5.55555556e-02 2.24719101e-01 1.31944444e+00]]


In [21]:
arr=np.random.randint(1,100,size=(5,5))
border = np.concatenate([
    arr[0, :],          # top row
    arr[1:-1, -1],      # right column (excluding corners)
    arr[-1, ::-1],      # bottom row reversed
    arr[-2:0:-1, 0]     # left column reversed (excluding corners)
])
print(border)


[15  3 64 26 37 52 29 27 92 36 36 31 97 42 68 82]


In [22]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
row_sum = np.sum(arr, axis=1)
print(row_sum)
col_sum = np.sum(arr, axis=0)
print(col_sum)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


In [24]:
arr=np.random.randint(1,100,size=(5,5))
print(arr)
arr_mean = np.mean(arr)
print(arr_mean)
arr_std = np.std(arr)
print(arr_std)
arr_median = np.median(arr)
print(arr_median)
arr_varience = np.var(arr)
print(arr_varience)

[[ 3  1 74  3 28]
 [79 45 12 50 31]
 [71 81 71 51 82]
 [51 48 98 99 25]
 [63 64 38 47 20]]
49.4
28.39859151436916
50.0
806.48


In [27]:
arr=np.arange(1,10).reshape(3,3)
print(arr)
norm=(arr-arr.mean())/arr.std()
print(norm)
print('mean:',norm.mean())
print('std:',norm.std())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
mean: 0.0
std: 1.0


In [29]:
arr =np.random.randint(1,100,size=(3,3))
print(arr)
v=np.array([1,2,3])
print(arr+v)


[[59 60 71]
 [30 37 55]
 [94 94 48]]
[[60 62 74]
 [31 39 58]
 [95 96 51]]


In [31]:
arr=np.arange(1,10).reshape(3,3)
arr_determinant=np.linalg.det(arr)
print(arr_determinant)
arr_inverse=np.linalg.inv(arr)
print(arr_inverse)
arr_eigenvalues,arr_eigenvectors=np.linalg.eig(arr)
print(arr_eigenvalues)
print(arr_eigenvectors)

-9.51619735392994e-16
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [34]:
matrix_a = np.random.randint(1, 100, size=(2, 3))
matrix_b = np.random.randint(1, 100, size=(3, 2))
matrix_multiplication = np.dot(matrix_a, matrix_b)
print(matrix_multiplication)

[[ 4085  9436]
 [ 4165 10667]]


In [36]:
arr=np.arange(1,17).reshape(4,4).flatten()
print(arr)
arr=np.arange(1,17).reshape(4,4)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [37]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

corners = [arr[0,0], arr[0,-1], arr[-1,0], arr[-1,-1]]
print(corners)

[np.int64(1), np.int64(3), np.int64(7), np.int64(9)]


In [38]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)
sorted_data = np.sort(data, order='age')
print("Sorted array:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]
